name: "Test safeio"

on: [push, pull_request]

jobs:
  test_conduit_algorithms:
    name: Build and test safeio
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'
          stack-no-global: true
      - run: |
          stack setup
          stack test
